// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderIntelligence.Infrastructure.Persistence;

#nullable disable

namespace TraderIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraderDbContext))]
    [Migration("20260818104430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("ManagerLogin")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoolSize")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("ProxyEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProxyHost")
                        .HasColumnType("text");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("integer");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("brokers", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.CanonicalInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("canonical_instruments", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.CopyIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestClOrdId")
                        .HasColumnType("text");

                    b.Property<decimal?>("DestFillPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("DestPositionId")
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExecutionIntentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LimitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("OrdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("RiskDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SourceEventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceLogin")
                        .HasColumnType("bigint");

                    b.Property<long>("SourcePositionId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SourceTradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StopTrigger")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("copy_intents", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.DestinationQuoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Ask")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Bid")
                        .HasColumnType("numeric");

                    b.Property<string>("CanonicalSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueInstrumentId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("VenueTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("destination_quotes", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.ExecutionIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClOrdId")
                        .HasColumnType("text");

                    b.Property<Guid>("CopyIntentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FillPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FixOrderId")
                        .HasColumnType("text");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RiskDecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeLots")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClOrdId")
                        .IsUnique();

                    b.ToTable("execution_intents", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.FixSessionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InboundSeq")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastInboundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastOutboundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OutboundSeq")
                        .HasColumnType("integer");

                    b.Property<bool>("OwnerHeld")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerInstance")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Qualifier")
                        .HasColumnType("integer");

                    b.Property<int>("ReconnectCount")
                        .HasColumnType("integer");

                    b.Property<string>("SenderCompId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderSubId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCompId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSubId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Qualifier")
                        .IsUnique();

                    b.ToTable("fix_sessions", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.KillSwitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SetBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("kill_switches", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.Mt5Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Equity")
                        .HasColumnType("numeric");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Leverage")
                        .HasColumnType("integer");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Margin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarginFree")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("RegistrationAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Login")
                        .IsUnique();

                    b.ToTable("mt5_accounts", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.Mt5Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Action")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<long>("DealTicket")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("DealTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Entry")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderTicket")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Swap")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeNative")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "DealTicket")
                        .IsUnique();

                    b.HasIndex("BrokerId", "Login", "DealTime");

                    b.ToTable("mt5_deals", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.Mt5Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<bool>("ConnectionsAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int>("CurrencyDigits")
                        .HasColumnType("integer");

                    b.Property<bool>("EnabledForAnalysis")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastDiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MarginCall")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarginStopOut")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanMapping")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Name")
                        .IsUnique();

                    b.ToTable("mt5_groups", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.Mt5Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionTicket")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceCurrent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceOpen")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceSl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceTp")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Profit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Swap")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimeUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VolumeNative")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "PositionTicket")
                        .IsUnique();

                    b.ToTable("mt5_positions_current", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.ReconstructedTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ClosedVolumeLots")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("DealCount")
                        .HasColumnType("integer");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryVwap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExitVwap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinalSl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinalTp")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossRealizedPnl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InitialSl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InitialTp")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InitialVolumeLots")
                        .HasColumnType("numeric");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxVolumeLots")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetRealizedPnl")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Swap")
                        .HasColumnType("numeric");

                    b.Property<bool>("WasAveragedDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasPartialClose")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasScaledIn")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Login", "PositionId", "OpenedAt");

                    b.ToTable("reconstructed_trades", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.RiskDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowFixSend")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CopyIntentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CopyIntentId");

                    b.ToTable("risk_decisions", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.ShadowOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CopyIntentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<long>("SourceLogin")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SourceVsShadowSlippage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Spread")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("shadow_orders", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.SourceSymbolMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "SourceSymbol")
                        .IsUnique();

                    b.ToTable("source_symbol_mappings", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.SyncCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<long?>("LastTicket")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Login", "Stream")
                        .IsUnique();

                    b.ToTable("sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.TraderScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AveragingDown")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BehaviorScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedXauTrades")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<decimal>("EarlyQualityScore")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("LastScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<bool>("LotEscalation")
                        .HasColumnType("boolean");

                    b.Property<bool>("Martingale")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Login")
                        .IsUnique();

                    b.ToTable("trader_scores", (string)null);
                });

            modelBuilder.Entity("TraderIntelligence.Domain.Entities.TraderScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BehaviorScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EarlyQualityScore")
                        .HasColumnType("numeric");

                    b.Property<long>("Login")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId", "Login", "RecordedAt");

                    b.ToTable("trader_score_history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
